server:
    port:8100

spring:
    redis:
        database: 0
        host: localhost
        port: 6379
        password:
        pool:
            max-active: 50
            max-wait: -1
            max-idle: 3
            min-idle: 1
        timeout: 5000
    application:
        name: testapp


logging:
    level:
        ROOT: INFO
        net.javacrumbs.shedlock: INFO
        com.jzwzz: DEBUG